## Hyperparameter flags for deepsurv model
PARAMS.DS <- flags(
    flag_integer('neurons.1', 128),
    flag_integer('neurons.2', 32),
    flag_integer('neurons.out', 1),
    flag_boolean("dropout.1",1),
    flag_numeric("drop.rate.1",0.2),
    flag_boolean("dropout.2",1),
    flag_numeric("drop.rate.2",0.2),
    flag_boolean("use_regularizer",0),
    flag_string('regularizer1.name',"l2"),    
    flag_numeric("reg.1", 0),
    flag_string('regularizer2.name',"l2"),    
    flag_numeric("reg.2", 0),
    flag_string("optimizer.name", "Adam"),
    flag_numeric("learn.rate", 0.001),
    flag_numeric("mx.we.con", 5),
    flag_string("act.fun.1", "relu"),
    flag_string("act.fun.2", "relu"),
    flag_string("act.fun.out", "sigmoid"),
    flag_string("loss.name", "focalLoss"),
    #flag_string("loss.name", "categorical_crossentropy"),
    #flag_string("metric.name", "f1score"),
    flag_string("metric.name",  "categorical_crossentropy"),
    flag_string("metric.name2", ""),
    flag_integer("batch", 256),
    flag_integer("epochs", 25),#200),
    #flag_boolean("shuffle", 1),
    flag_boolean("verbose", 1),
    ##flag_boolean("use.valSplit",0),    
    flag_boolean("use.valData",1),
    flag_numeric("ratio_train",0.8),
    flag_numeric("ratio_val",0.2),
    flag_string("model.name", "multistate"),
    flag_boolean("use.callback",0),
    flag_boolean("save.model",0),
    flag_boolean("load.model",0),
    flag_boolean("plot.model",1)
)
